services:
  redwood:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: base
    command: yarn rw dev
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    ports:
      - '8910:8910'
    depends_on:
      - db
      - smtp
    environment:
      - DATABASE_URL=mysql://redwood:redwood@db:3306/redwood
      - TEST_DATABASE_URL=mysql://redwood:redwood@db:3306/redwood_test
      - SESSION_SECRET=super_secret_session_key_change_me_in_production_please
      - APP_NAME=researchequals-test-env
      - NODE_ENV=development
      - REDWOOD_API_HOST=0.0.0.0
      - SMTP_HOST=smtp
      - SMTP_PORT=1025

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: redwood
      MYSQL_DATABASE: redwood
      MYSQL_USER: redwood
      MYSQL_PASSWORD: redwood
    ports:
      - '3306:3306'
    volumes:
      - mysql:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

  smtp:
    image: mailhog/mailhog
    ports:
      - '1025:1025'  # SMTP server
      - '8025:8025'  # Web UI

volumes:
  node_modules:
  mysql:
